name: Build TypeScript and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Verify compiled JavaScript files exist
        run: |
          echo "Checking compiled JavaScript files..."
          ls -la src/*.js || echo "No JS files found in src/"
          
      - name: Prepare deployment directory
        if: github.event_name != 'pull_request'
        run: |
          echo "Creating deployment directory..."
          mkdir -p _site
          
          # Copy all files except node_modules and .git
          echo "Copying files to _site..."
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='_site' ./ _site/
          
          # List compiled JS files to verify
          echo "Verifying JS files in _site/src/..."
          ls -la _site/src/*.js || echo "Warning: No JS files in _site/src/"

      - name: Upload compiled JavaScript as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-js
          path: |
            src/**/*.js
            src/**/*.js.map
          if-no-files-found: error

      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: github.event_name != 'pull_request'

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
